apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: sustainability-chatbot
  annotations:
    "scenarios.ai.sap.com/description": "Sustainability Chatbot using FLAN-T5"
    "scenarios.ai.sap.com/name": "Sustainability"
  labels:
    "scenarios.ai.sap.com/id": "sustainability"
    "ai.sap.com/version": "1.0.0"
spec:
  template:
    apiVersion: serving.kserve.io/v1beta1
    kind: InferenceService
    metadata:
      name: sustainability-chatbot
    spec: |
      predictor:
        minReplicas: 1
        maxReplicas: 1
        model:
          modelFormat:
            name: huggingface
          runtime: ai-core-llm
          uri: "google/flan-t5-small"
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
          limits:
            memory: "8Gi"
            cpu: "4"