apiVersion: ai.sap.com/v1alpha1
kind: Serving
metadata:
  name: sustainability-chatbot
  annotations:
    ai.sap.com/description: "Sustainability Chatbot using FLAN-T5"
    ai.sap.com/version: "1.0.0"
    ai.sap.com/author: "Akshay Poojary"
spec:
  template:
    apiVersion: serving.kserve.io/v1beta1
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "3"
    spec:
      predictor:
        containers:
        - name: kserve-container
          image: ghcr.io/akshaypo3/sustainability-sap-backend:latest
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: PORT
              value: "5000"
            - name: MODEL_NAME
              value: "google/flan-t5-small"
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: "1"
              memory: 2Gi
