apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: sustainability-chatbot
spec:
  template: |
    {
      "apiVersion": "serving.kserve.io/v1beta1",
      "kind": "InferenceService",
      "metadata": {
        "name": "sustainability-chatbot"
      },
      "spec": {
        "predictor": {
          "containers": [
            {
              "name": "kserve-container",
              "image": "ghcr.io/akshaypo3/sustainability-chatbott:light-cpu",
              "ports": [
                {
                  "containerPort": 5000
                }
              ],
              "env": [
                {
                  "name": "PORT",
                  "value": "5000"
                }
              ]
            }
          ]
        }
      }
    }