name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
    paths:
      - 'sap-deployment/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./sap-deployment
        push: true
        tags: ghcr.io/akshaypo3/sustainability-chatbott:light-cpu

    - name: Test Docker Image
      run: |
        echo "Testing the Docker image..."
        docker run -d --name test-bot -p 5001:5000 ghcr.io/akshaypo3/sustainability-chatbott:light-cpu
        sleep 15
        echo "Health check:"
        curl -s http://localhost:5001/health || echo "Health check failed - container might still be starting"
        docker stop test-bot
        docker rm test-bot

    - name: Success Message
      run: |
        echo "✅ SUCCESS: Docker image built and pushed!"
        echo "📦 Image URL: ghcr.io/akshaypo3/sustainability-chatbott:light-cpu"
        echo "🚀 Run locally: docker run -p 5000:5000 ghcr.io/akshaypo3/sustainability-chatbott:light-cpu"
        echo "💡 Deploy to: Render.com, Railway.app, or Heroku"