name: Build and Deploy to SAP AI Core

on:
  push:
    branches: [ "main" ]
    paths:
      - 'sap-deployment/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./sap-deployment
        push: true
        tags: ghcr.io/akshaypo3/sustainability-chatbott:light-cpu

    - name: Install dependencies for SAP API call
      run: |
        sudo apt-get update
        sudo apt-get install -y jq curl

    - name: Deploy to SAP AI Core via API
      env:
        SAP_CLIENT_ID: ${{ secrets.SAP_CLIENT_ID }}
        SAP_CLIENT_SECRET: ${{ secrets.SAP_CLIENT_SECRET }}
        SAP_AUTH_URL: ${{ secrets.SAP_AUTH_URL }}
        SAP_API_URL: ${{ secrets.SAP_API_URL }}
      run: |
        # Get authentication token
        echo "Getting SAP authentication token..."
        TOKEN_RESPONSE=$(curl -s -X POST "$SAP_AUTH_URL/oauth/token" \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "grant_type=client_credentials&client_id=$SAP_CLIENT_ID&client_secret=$SAP_CLIENT_SECRET")
        
        TOKEN=$(echo $TOKEN_RESPONSE | jq -r '.access_token')
        
        if [ "$TOKEN" = "null" ] || [ -z "$TOKEN" ]; then
          echo "Error: Failed to get access token"
          echo "Response: $TOKEN_RESPONSE"
          exit 1
        fi
        
        echo "Successfully obtained SAP token"
        
        # Deploy to SAP AI Core using the correct endpoint
        echo "Deploying serving template to SAP AI Core..."
        DEPLOY_RESPONSE=$(curl -s -w "\n%{http_code}" -X POST "$SAP_API_URL/v2/lm/servingtemplates" \
          -H "Authorization: Bearer $TOKEN" \
          -H "Content-Type: multipart/form-data" \
          -F "file=@sap-deployment/serving.yaml")
        
        HTTP_CODE=$(echo "$DEPLOY_RESPONSE" | tail -n1)
        RESPONSE_BODY=$(echo "$DEPLOY_RESPONSE" | sed '$d')
        
        echo "HTTP Status Code: $HTTP_CODE"
        echo "Response: $RESPONSE_BODY"
        
        if [ "$HTTP_CODE" -ge 200 ] && [ "$HTTP_CODE" -lt 300 ]; then
          echo "✅ Deployment successful!"
        else
          echo "❌ Deployment failed with status code $HTTP_CODE"
          exit 1
        fi
        