name: Build & Deploy to SAP AI Core

on:
  push:
    branches: [ "main" ]
    paths:
      - 'sap-deployment/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & Push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./sap-deployment
        push: true
        tags: ghcr.io/${{ github.repository }}:latest

    - name: Deploy to SAP AI Core
      env:
        SAP_CLIENT_ID: ${{ secrets.SAP_CLIENT_ID }}
        SAP_CLIENT_SECRET: ${{ secrets.SAP_CLIENT_SECRET }}
        SAP_SERVICE_KEY: ${{ secrets.SAP_SERVICE_KEY }}
      run: |
        pip install aicore --quiet
        echo "$SAP_SERVICE_KEY" > service_key.json
        aicore login --client-id "$SAP_CLIENT_ID" --client-secret "$SAP_CLIENT_SECRET" --service-key service_key.json
        aicore deployment create -f sap-deployment/serving.yaml

