name: Build and Deploy to SAP AI Core

on:
  push:
    branches: [ "main" ]
    paths:
      - 'sap-deployment/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Build Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./sap-deployment
        push: true
        tags: ghcr.io/akshaypo3/sustainability-chatbott:light-cpu  

    - name: Deploy to SAP AI Core
      env:
        SAP_CLIENT_ID: ${{ secrets.SAP_CLIENT_ID }}
        SAP_CLIENT_SECRET: ${{ secrets.SAP_CLIENT_SECRET }}
        SAP_AUTH_URL: ${{ secrets.SAP_AUTH_URL }}  
        SAP_API_URL: ${{ secrets.SAP_API_URL }}    
      run: |
        # Install SAP CLI
        pip install sap-ai-core-sdk
        
        # Login to SAP
        sapcli login --client-id "$SAP_CLIENT_ID" --client-secret "$SAP_CLIENT_SECRET" --auth-url "$SAP_AUTH_URL" --api-url "$SAP_API_URL"
        
        # Deploy with correct filename
        sapcli deployment create -f sap-deployment/serving-template.yaml  # ← FIXED FILENAME