name: SAP AI Core Deployment

on:
  push:
    branches: [ "main" ]
    paths:
      - 'sap-deployment/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./sap-deployment
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          secrets: |
            ${{ secrets.GITHUB_TOKEN }}

      - name: Login to SAP
        env:
          SAP_CLIENT_ID: ${{ secrets.SAP_CLIENT_ID }}
          SAP_CLIENT_SECRET: ${{ secrets.SAP_CLIENT_SECRET }}
        run: |
          pip install sap-ai-core-sdk
          sapcli login --client-id "$SAP_CLIENT_ID" --client-secret "$SAP_CLIENT_SECRET"

      - name: Deploy to SAP AI Core
        run: |
          sapcli deployment create -f sap-deployment/serving.yaml