name: Build & Push backend image

on:
  push:
    branches: [ "main" ]
    paths:
      - 'sap-deployment/**'

jobs:
  push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # needed to push to GHCR
    env:
      IMAGE_TAG: ghcr.io/akshaypo3/sustainability-sap-backend:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ./sap-deployment
          push: true
          tags: ${{ env.IMAGE_TAG }}
          platforms: linux/amd64
